Adapt getErased() (used in type inference) to our weird substitution rules.
getErased() is called by getEffectiveAnnotations(), which is called by
getEffectiveAnnotationInHierarchy(), which is called by
DefaultTypeArgumentInference.clampToLowerBound().

Consequently, this commit fixes problems with inputs like the following:
https://github.com/jspecify/jspecify/commit/9da93c51a4d3c8bb87a10f42eb45dbce091c8a7e

This comes up in Guava. It also comes up in Truth (when compiled against
an annotated Guava).

This fix is probably the wrong thing: Ultimately, we should probably fix
the bounds themselves, as noted previously:
https://github.com/jspecify/checker-framework/issues/4#issuecomment-729147609

(So far, though, my efforts to fix that have triggered new problems.
Still, I should try more someday.)

I also note that, if I'm not mistaken, this commit *creates* an error in
Guava:

```
guava/src/com/google/common/collect/Sets.java:776: error: [nullness] incompatible parameter types for parameter 0 in lambda expression.
        return Stream.concat(set1.stream(), set2.stream().filter(e -> !set1.contains(e)));
                                                                 ^
  found   : ? extends E
  required: <captured wildcard>
```

That looks to be here:
https://github.com/google/guava/blob/7112c0339419289cf7175f304d092571c5913ec2/guava/src/com/google/common/collect/Sets.java#L778

Still, I'm seeing a net *decrease* in errors in Guava. Plus, I should be
able to remove some existing workarounds, like this one:
https://github.com/google/guava/commit/189a410bf2ece47d0994ae39cabefbb30a809a32#diff-3ef68811fc409685d4bb4ce7c7551392290fcf9e01643b205e46b6bf97f2cce7R699